### ISSUE TITLE
LCD screen bug

### ISSUE THREAD

**Issue by bobwmcgrath** [mit-drl/e-vent#63]
After a few minutes of run time my LCD screen starts to display garbage.  Is anybody else experiencing this?  The bug occurs after homing is complete.  I enter the EX_STATE and then since I am just emulating pressure feedback manually on my desk several alarms occur.  After a few minutes the screen displays nonsense.  
![95481502_286422802518683_7599466072130977792_n](https://user-images.githubusercontent.com/29110580/80969860-e6586e80-8ddf-11ea-862d-1a4a76dc2be0.jpg)

**Comment by amadoantonini** [comment]
Can you elaborate on how you are emulating the pressure signal?

**Comment by bobwmcgrath** [comment]
I have attached a syringe to the sensor with heat shrink.  I have also been able to circumvent this bug for testing purposes by commenting out everything inside of the handleErrors function.
![95619759_236519177411442_764844984342937600_n](https://user-images.githubusercontent.com/29110580/81006502-461d3c80-8e15-11ea-853a-877706119f26.jpg)

**Comment by amadoantonini** [comment]
When the display starts displaying garbage, does the system continue running?

**Comment by bobwmcgrath** [comment]
Judging by the beeps and serial output, it seems as though it does respond to buttons, knobs, and the pressure sensor.

**Comment by amadoantonini** [comment]
It could be trying to write a bad value. One thing you can do to check is to add a serial print in [the place where we write to the LCD](https://github.com/mit-drl/e-vent/blob/master/Display.cpp#L194) to see what it's trying to do. E.g.
```
Serial.print(row); Serial.print(", "); Serial.print(col); Serial.print(": "); Serial.println(printable);
```

**Comment by bobwmcgrath** [comment]
With the added debugging code, the serial output looks about the same weather the screen is working or not.  I have copied a few lines below from each scenario.  

screen working
22:14:36.213 -> 0, 11: Pressure:
22:14:36.247 -> 17.69,	1.02,	0,	  0,	  0.00
22:14:36.247 -> 0, 11: Pressure:
22:14:36.282 -> 17.72,	1.02,	0,	  0,	  0.00
22:14:36.282 -> 0, 11: Pressure:
22:14:36.316 -> 17.75,	1.02,	0,	  0,	  0.00
22:14:36.316 -> 0, 11: Pressure:

screen broken
22:13:13.221 -> 269.86,	1.02,	0,	  0,	  0.25
22:13:13.221 -> 0, 11: Pressure:
22:13:13.255 -> 269.89,	1.02,	0,	  0,	  0.25
22:13:13.255 -> 0, 11: Pressure:
22:13:13.289 -> 269.92,	1.02,	0,	  0,	  0.00
22:13:13.289 -> 0, 11: Pressure:
22:13:13.323 -> 269.95,	1.02,	0,	  0,	  0.00
22:13:13.323 -> 0, 11: Pressure:

**Comment by bobwmcgrath** [comment]
Also the bug seems to persist even while cycling normally through states and with all the error handling commented out.

**Comment by amadoantonini** [comment]
Sometimes the screen can display garbage if a cable is loose. Do you observe this behavior consistently after a few minutes? And does it go away with a simple restart?

**Comment by bobwmcgrath** [comment]
It seems to take a random amount of time and goes away with a restart.  It looks like I get the same error when I unplug the screen and plug it back in, so I think I will close this comment though I did just post another one.
