### ISSUE TITLE
Display.cpp  wirteBPM method

### ISSUE THREAD

**Issue by srinivasboppu** [mit-drl/e-vent#66]
void Display::writeBPM(const int& bpm) {
  const int bpm_c = constrain(bpm, 0, 99);
  char buff[12];
  sprintf(buff, "%2s=%2s      ", getLabel(BPM).c_str(), toString(VOLUME, bpm_c).c_str());
  write(elements_[BPM].row, elements_[BPM].col, buff);
}

here, the sprintf line is wrong, it should be:

  sprintf(buff, "%2s=%2s      ", getLabel(BPM).c_str(), toString(BPM, bpm_c).c_str());

**Comment by amadoantonini** [comment]
Thanks for the catch!
The behavior is still correct because `toString(VOLUME, bpm_c)` and `toString(BPM, bpm_c)` do the same thing. But I've fixed it in #67.

**Comment by teddyort** [comment]
Fixed in https://github.com/mit-drl/e-vent/pull/67. Closing.
