### ISSUE TITLE
On/off button does not restart the system

### ISSUE THREAD

**Issue by abukhalaf** [mit-drl/e-vent#73]
The on/off button turns off the system, but does not restart it; instead the confirm button has this function.

**Comment by amadoantonini** [comment]
@abukhalaf, this behavior is intended. It is not a bug.

**Comment by teddyort** [comment]
To clarify, the button is not actually an on/off button. 

The on/off button was removed from the last hardware release which included a push-button on the low-voltage power input. Instead it was replaced with a momentary "Stop" button and the other button is a "Set/Start" button. This was done for regulatory reasons.

The summarize, the intended behavior is that the system is stopped by holding the "stop" button, and then started again using the "Set/Start" button.

**Comment by abukhalaf** [comment]
Excellent documentation of the intended behavior. Thanks!  Closing the issue.
